services:
  - type: web
    name: interview-be
    env: python
    pythonVersion: "3.10"
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
